export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT='AUTH_LOGOUT';

export const INIT_SEARCH='INIT_SEARCH';
export const SEARCH_PROFILE_START='SEARCH_PROFILE_START';
export const SEARCH_PROFILE_SUCCESS='SEARCH_PROFILE_SUCCESS';
export const SEARCH_PROFILE_FAIL='SEARCH_PROFILE_FAIL';

export const PLANET_OPTION_START='PLANET_OPTION_START';
export const PLANET_OPTION_FAIL='PLANET_OPTION_FAIL';
export const PLANET_OPTION_SUCCESS='PLANET_OPTION_SUCCESS';



export const PLANET_INFO_START='PLANET_INFO_START';
export const PLANET_INFO_SUCCESS='PLANET_INFO_SUCCESS';
export const PLANET_INFO_FAIL='PLANET_INFO_FAIL';

